export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          display: "flex",
          flexDirection: "column",
          minHeight: "100vh",
          margin: 0,
          padding: 0,
        }}
      >
        <header
          style={{
            position: "fixed",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            backgroundColor: "lightblue",
            padding: "1rem",
            top: "0",
            left: "0",
            right: "0",
            width: "100%",
            zIndex: 1000,
            textAlign: "center",
          }}
        >
          <p> This is Header</p>
        </header>
        <main
          style={{
            flex: "1",
            width: "100%",
            paddingTop: "4rem", // Adjust based on header height
            paddingBottom: "4rem", // Adjust based on footer height
            boxSizing: "border-box",
            overflow: "auto",
          }}
        >
          {children}
        </main>
        <footer
          style={{
            position: "fixed",
            bottom: "0",
            left: "0",
            right: "0",
            width: "100%",
            backgroundColor: "GhostWhite",
            padding: "1rem",
            zIndex: 1000,
            textAlign: "center",
          }}
        >
          <p>This is Footer </p>
        </footer>
      </body>
    </html>
  );
}
